# Generated by Django 4.1 on 2022-09-29 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
