# Generated by Django 4.1 on 2022-09-29 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0002_catalogitem_is_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogitem',
            name='is_finished',
        ),
    ]
